# -*- coding: utf-8 -*-
"""Limpieza MES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZmB4pcc_T1ZXOWgZlpF7eAcyUWAr2x9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('C:\Users\Alejandro\OneDrive\Documents\GitHub\Bootcamp2026-1\Documentos\MES_1225.xlsx')
df.head(20)

df = df.drop([0,1,2,3,4,5,6])
print(df)

# df

# df.info()

# df[df['Product'].isna() == True]

# df['Product'].unique()

# df.iloc[16]

# 15*12*13

# len(df[df['Country']=='Colombia'])#['Product'].nunique()